### ISSUE TITLE
Could you add me in the organization ?

### ISSUE THREAD

**Issue by locness3** [Rexxt-Software/neon-browser#2]
Since Myst Software and Rexxt Softare merged, I would like to be in this organization. And what we do with the old Myst Software site ?

**Comment by locness3** [comment]
Sorry for saying that here

**Comment by locness3** [comment]
@tamere

**Comment by locness3** [comment]
@sorry

**Comment by Rexxt** [comment]
Closing old myst software site.
Inviting in a second.
